2012-12-06 23:40:48 Error: Fatal Error (4): syntax error, unexpected '{' in [C:\xampp\htdocs\projects\app\Controller\UsersController.php, line 23]
2012-12-06 23:40:48 Error: [FatalErrorException] syntax error, unexpected '{'
#0 C:\xampp\htdocs\projects\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 23)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 23, Array)
#2 C:\xampp\htdocs\projects\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 23, Array)
#3 C:\xampp\htdocs\projects\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-08 10:38:15 Error: Fatal Error (4): syntax error, unexpected '<' in [C:\xampp\htdocs\projects\app\View\Users\profile.ctp, line 57]
2012-12-08 10:38:15 Error: [FatalErrorException] syntax error, unexpected '<'
#0 C:\xampp\htdocs\projects\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 57)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 57, Array)
#2 C:\xampp\htdocs\projects\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 57, Array)
#3 C:\xampp\htdocs\projects\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-08 10:51:36 Error: Fatal Error (4): syntax error, unexpected '<' in [C:\xampp\htdocs\projects\app\View\Users\profile.ctp, line 80]
2012-12-08 10:51:36 Error: [FatalErrorException] syntax error, unexpected '<'
#0 C:\xampp\htdocs\projects\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 80)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 80, Array)
#2 C:\xampp\htdocs\projects\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 80, Array)
#3 C:\xampp\htdocs\projects\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-08 11:51:07 Error: Fatal Error (1): Call to a member function User() on a non-object in [C:\xampp\htdocs\projects\app\Controller\ProjectsController.php, line 71]
2012-12-08 11:51:07 Error: [FatalErrorException] Call to a member function User() on a non-object
#0 C:\xampp\htdocs\projects\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 71)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 71, Array)
#2 C:\xampp\htdocs\projects\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 71, Array)
#3 C:\xampp\htdocs\projects\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-08 11:52:35 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ProjectsUsers.user_id' in 'where clause'
#0 C:\xampp\htdocs\projects\lib\Cake\Model\Datasource\DboSource.php(459): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\projects\lib\Cake\Model\Datasource\DboSource.php(425): DboSource->_execute('SELECT `User`.`...', Array)
#2 C:\xampp\htdocs\projects\lib\Cake\Model\Datasource\DboSource.php(669): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 C:\xampp\htdocs\projects\lib\Cake\Model\Datasource\DboSource.php(1080): DboSource->fetchAll('SELECT `User`.`...', false)
#4 C:\xampp\htdocs\projects\lib\Cake\Model\Model.php(2630): DboSource->read(Object(User), Array)
#5 C:\xampp\htdocs\projects\app\Controller\ProjectsController.php(73): Model->find('all', Array)
#6 [internal function]: ProjectsController->view('1')
#7 C:\xampp\htdocs\projects\lib\Cake\Controller\Controller.php(485): ReflectionMethod->invokeArgs(Object(ProjectsController), Array)
#8 C:\xampp\htdocs\projects\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#9 C:\xampp\htdocs\projects\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(ProjectsController), Object(CakeRequest), Object(CakeResponse))
#10 C:\xampp\htdocs\projects\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
2012-12-08 12:55:26 Error: Fatal Error (4): syntax error, unexpected T_VARIABLE in [C:\xampp\htdocs\projects\app\Controller\ProjectsController.php, line 76]
2012-12-08 12:55:26 Error: [FatalErrorException] syntax error, unexpected T_VARIABLE
#0 C:\xampp\htdocs\projects\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 76)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 76, Array)
#2 C:\xampp\htdocs\projects\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 76, Array)
#3 C:\xampp\htdocs\projects\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-08 12:55:43 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\projects\app\Controller\ProjectsController.php, line 77]
2012-12-08 12:55:43 Error: [FatalErrorException] syntax error, unexpected ';'
#0 C:\xampp\htdocs\projects\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 77)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 77, Array)
#2 C:\xampp\htdocs\projects\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 77, Array)
#3 C:\xampp\htdocs\projects\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-08 13:20:08 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ProjectsUsers.group_id' in 'field list'
#0 C:\xampp\htdocs\projects\lib\Cake\Model\Datasource\DboSource.php(459): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\projects\lib\Cake\Model\Datasource\DboSource.php(425): DboSource->_execute('SELECT `Project...', Array)
#2 C:\xampp\htdocs\projects\lib\Cake\Model\Datasource\DboSource.php(669): DboSource->execute('SELECT `Project...', Array, Array)
#3 C:\xampp\htdocs\projects\lib\Cake\Model\Datasource\DboSource.php(1080): DboSource->fetchAll('SELECT `Project...', false)
#4 C:\xampp\htdocs\projects\lib\Cake\Model\Model.php(2630): DboSource->read(Object(Project), Array)
#5 C:\xampp\htdocs\projects\app\Controller\ProjectsController.php(74): Model->find('first', Array)
#6 [internal function]: ProjectsController->view('1')
#7 C:\xampp\htdocs\projects\lib\Cake\Controller\Controller.php(485): ReflectionMethod->invokeArgs(Object(ProjectsController), Array)
#8 C:\xampp\htdocs\projects\lib\Cake\Routing\Dispatcher.php(186): Controller->invokeAction(Object(CakeRequest))
#9 C:\xampp\htdocs\projects\lib\Cake\Routing\Dispatcher.php(161): Dispatcher->_invoke(Object(ProjectsController), Object(CakeRequest), Object(CakeResponse))
#10 C:\xampp\htdocs\projects\app\webroot\index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
2012-12-08 13:22:23 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\projects\app\Controller\ProjectsController.php, line 75]
2012-12-08 13:22:23 Error: [FatalErrorException] Call to a member function find() on a non-object
#0 C:\xampp\htdocs\projects\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 75)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 75, Array)
#2 C:\xampp\htdocs\projects\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 75, Array)
#3 C:\xampp\htdocs\projects\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-08 13:24:47 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\projects\app\Controller\ProjectsController.php, line 75]
2012-12-08 13:24:47 Error: [FatalErrorException] Call to a member function find() on a non-object
#0 C:\xampp\htdocs\projects\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 75)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 75, Array)
#2 C:\xampp\htdocs\projects\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 75, Array)
#3 C:\xampp\htdocs\projects\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2012-12-08 13:26:02 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\projects\app\Controller\ProjectsController.php, line 75]
2012-12-08 13:26:02 Error: [FatalErrorException] Call to a member function find() on a non-object
#0 C:\xampp\htdocs\projects\lib\Cake\Error\ErrorHandler.php(161): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 75)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 75, Array)
#2 C:\xampp\htdocs\projects\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 75, Array)
#3 C:\xampp\htdocs\projects\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
